version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/OnParDev.Mcp.Api"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/OnParDev.Mcp.Api/ClientApp"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
