name: Flyway Migrations

on:
  pull_request:
    paths:
      - 'flyway/**'

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Compose
        run: docker compose --version
      - name: Run Flyway migrations
        run: |
          docker compose up -d db
          docker compose run --rm flyway
          docker compose down
