name: PR Verification

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: OnParDev.Mcp.Api/ClientApp
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: OnParDev.Mcp.Api/ClientApp/.nvmrc
          cache: 'npm'
          cache-dependency-path: OnParDev.Mcp.Api/ClientApp/package-lock.json
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm test

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Check for backend code changes
        id: backend_changes
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }}
          FILE_DIFF=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- '*.cs' '*.csproj' '*.sln')
          if [ -z "$FILE_DIFF" ]; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          CODE_DIFF=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --unified=0 -- '*.cs' |
            grep -E '^[+-]' |
            grep -vE '^\+\+\+|^---' |
            grep -vE '^[+-]\s*(//|///|/\*|\*|\*/)'
          )

          if [ -n "$CODE_DIFF" ] || [ -n "$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- '*.csproj' '*.sln')" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Skip backend if no code changes
        if: steps.backend_changes.outputs.changed == 'false'
        run: echo "No backend code changes detected. Skipping backend checks."
      - name: Restore
        if: steps.backend_changes.outputs.changed == 'true'
        run: dotnet restore
      - name: Lint
        if: steps.backend_changes.outputs.changed == 'true'
        run: dotnet format --no-restore --verify-no-changes
      - name: Build
        if: steps.backend_changes.outputs.changed == 'true'
        run: dotnet build --no-restore --configuration Release
      - name: Test
        if: steps.backend_changes.outputs.changed == 'true'
        run: dotnet test --no-build --configuration Release --verbosity normal
