name: CI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - 'iac/**'

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: frontend/.nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: backend/global.json
      - name: Restore
        run: dotnet restore backend.sln
      - name: Build
        run: dotnet build backend.sln --no-restore
      - name: Test
        run: dotnet test backend.sln --no-build
